### ISSUE TITLE
Improvement: Create Bundle for SharedFlows

### ISSUE THREAD

**Issue by peruzzof** [apigee/apigeecli#104]
Hi, I am already using apigeecli in my DevOps CI/CD pipeline to manage everything related to proxies (create new revision, deploy, update KVMs..). And for the apis I am using the command "apigeecli apis create bundle" to generate the .zip file straight from the directory structure that is stored in a Git repo.
Now we have a scenario to use the SharedFlows and I couldnt find a "sharedflows create bundle" option, I must add the step to generate the zip file before using the CLI.

It is possible to create a command similar that will generate the bundle from a directory as a single step?

Thanks,
Fabio

**Comment by srinandan** [comment]
I have a draft version that works. I can create a beta version for testing

**Comment by peruzzof** [comment]
Perfect, I can test as soon as it is published.

**Comment by srinandan** [comment]
Here is the link: https://github.com/apigee/apigeecli/releases/tag/v1.113.6-beta

**Comment by peruzzof** [comment]
Thanks, I updated my pipeline and it worked as expected.

I also noted that for sharedflow we are using -f for the path and -p for the zip, but with the apis create bundle we use -p for the path and -z for the zip. Not sure if you prefer to have a breaking change in sharedflow just to have a standard in the flags.

**Comment by srinandan** [comment]
Thanks for spotting that, I was thinking about the same thing. I think what I did with `apis` can be improved. I'm thinking of eliminating the flag `--proxy-zip-folder` or `-f`. I can use `TmpDir()` and use a `/tmp` or `C:\Temp` and not require that parameter. Then I can make `apis` match sharedflows. WDYT?

**Comment by ssvaidyanathan** [comment]
> Thanks for spotting that, I was thinking about the same thing. I think what I did with `apis` can be improved. I'm thinking of eliminating the flag `--proxy-zip-folder` or `-f`. I can use `TmpDir()` and use a `/tmp` or `C:\Temp` and not require that parameter. Then I can make `apis` match sharedflows. WDYT?

Would this be a breaking change? What if others are using `-f`?

**Comment by srinandan** [comment]
I was wrong. We do have v1.113 which was released ~2 weeks ago. I prefer the method in `sharedflows` of not adding another flag. But I will do whatever is the general consensus.

**Comment by peruzzof** [comment]
Sorry, I wasn't familiar with the TmpDir(). I agree that is better than the flag that we introduced earlier.
Even with the probably breaking change I think that is better to have a consistent set of parameters and the one in shared flow looks cleaner.

So, in my opinion, you can change the apis to match shared flow.

**Comment by srinandan** [comment]
v1.114 published with the changes.
