### ISSUE TITLE
Apigee TLSKeyStore/KeyAliases - failed to parse x509 certificate

### ISSUE THREAD

**Issue by psaini0212** [apigee/apigeecli#128]
Hi Team,

We need to enable mTLS communication from our Apigee env.
For that I am trying to create a TLSKeyStore and KeyAliases in it.
I am using Apigee CLI for it (https://github.com/apigee/apigeecli)
The Keystore creation is all OK.
However when I try to create a KeyAlias inside it - I get below

apigeecli keyaliases create -e sbx -o $APIGEE_ORG  -k test2 -s test2alias1 -f pem
ERROR: 2022/12/04 14:53:19 httpclient.go:372: status code 400, error in response: {
  "error": {
    "code": 400,
    "message": "failed to parse x509 certificate",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.RequestInfo",
        "requestId": "2247604128365081154"
      }
    ]
  }
}

Error: error in response

test2 :- is my Keystore name in sbx env.

test2alias1 :-  is the pem file which has key and cert appended in it.

The "apigeecli keyaliases create" command accepts only one file i think? and hence the I have added both key and cert in one single file

like this -

-----BEGIN CERTIFICATE-----
REDACTED
-----END CERTIFICATE-----
-----BEGIN PRIVATE KEY-----
REDACTED
-----END PRIVATE KEY-----

If I do this via GUI which accept both cert and key file separately, it works fine - the alias gets created.
(Keystore test1 and alias test was created via GUI ).

However we need to do it programatically, hence command line is the only option for us to call it in our scripts.

Please help us here, how can we create keyaliases with ApigeeCLI, what's missing here, pls?

**Comment by srinandan** [comment]
I see the problem. The CLI doesn't support key and cert. Cert only works, PFX works. I will work on it and update here.

**Comment by psaini0212** [comment]
Thank you @srinandan

**Comment by srinandan** [comment]
Can you please try this [beta release](https://github.com/apigee/apigeecli/releases/tag/v1.116.1-beta)? I will include these changes in v1.116.

**Comment by srinandan** [comment]
This is now available with v1.116
