### ISSUE TITLE
Feature Request: Function to Update KVM Entries

### ISSUE THREAD

**Issue by psaini0212** [apigee/apigeecli#150]
Hi @srinandan 

It's a feature request.
Ca we have an update function (PUT) which update the existing KVM entry, please?
The function could take the same input variable as we have in the CreateEntry function - https://github.com/apigee/apigeecli/blob/main/client/kvm/entries.go#L41
The use case we have is - suppose we have an exiting KVM with multiple entries, and we have to update the value for one of the entry.
We can basically call it in a loop to update the existing entries with the new value.
I haven't tried using the existing "CreateEntry" in this scenario but then my assumption is that it will fail with error the entry already exists? am I correct?
It could be similar to as you have done for targetServers - both Create and Update, Thank you
https://github.com/apigee/apigeecli/blob/main/client/targetservers/targetservers.go#L63-L72

**Comment by srinandan** [comment]
KVMs could have millions of [entries](https://cloud.google.com/apigee/docs/api-platform/reference/limits#persistence:-cache,-kvm,-property-sets). We'd have to loop through the full list and potentially impact the quota for management APIs. 

We have logged a feature request to solve this server-side (i.e., the ability to add a PUT for KVM entries).
