### ISSUE TITLE
content-type is missing when uploading bundle

### ISSUE THREAD

**Issue by srinandan** [apigee/apigeecli#154]

**Comment by srinandan** [comment]
@Helcaraxan - there are some errors reported in importing proxies. I might have a rollback v1.117 (proxy import changes). 

One of the errors was a missing content-type [here](https://github.com/apigee/apigeecli/blob/main/client/apis/apis.go#L560). I'm still investigating.

**Comment by Helcaraxan** [comment]
Hello @srinandan.

Am looking at this myself. It would be really helpful if the reported errors came with an error message or other form of failure.

Based on the [documentation of the REST API](https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.apis/create) there is no specific content-type header required when uploading a new bundle.

I did not run into any such issues while testing that change. That's not to say that there's nothing wrong but it's hard for me to help to troubleshoot this issue that I may have caused without further information.

**Comment by Helcaraxan** [comment]
See #155.

**Comment by srinandan** [comment]
This did not fix it.

I have the details:

```
apigeecli apis create bundle -n nandan2 -f test_proxy.zip -t $token
ERROR: 2023/02/09 18:55:14 httpclient.go:375: status code 400, error in response: {
  "error": {
    "code": 400,
    "message": "bundle contains errors",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/edge.configstore.bundle.BadBundle",
        "violations": [
          {
            "filename": "test_proxy.zip",
            "description": "zip entry in bundle has invalid path"
          },
          {
            "description": "The proxy must contain a ProxyEndpoint"
          }
        ]
      },
      {
        "@type": "type.googleapis.com/google.rpc.RequestInfo",
        "requestId": "12507537211223237036"
      }
    ]
  }
}
```

apigeecli version v1.118.1-beta, Git: a2cfb3c153c35d5e10e58002120df12585be43c6

**Comment by Helcaraxan** [comment]
That error would seem to indicate that your zip is malformed, not that the apigeecli is not behaving as it should.

```
"description": "The proxy must contain a ProxyEndpoint"
```

Or am I mistaken?

**Comment by srinandan** [comment]
User error, I gave the wrong command. It should be: 
```
apigeecli apis create bundle -n nandan2 -p test_proxy.zip -t $token
```

And I get this error:

```
Error: zip: not a valid zip file
```

And that is not correct. I'm adding some validations to the code now.

**Comment by srinandan** [comment]
The zip is valid. It is in the `test` folder. I use this for all my unit tests. The zip is good. Btw, this only happens in Linux and not on Mac. Which is strange.

**Comment by srinandan** [comment]
Some of the user errors reported were actually not a problem with the code, but rather incorrect usage of the CLI. I have added validations to improve the experience. We are still not out of the woods. I'm asking the folks to try with the right command.

**Comment by Helcaraxan** [comment]
@srinandan any update from your other users around the erroneous behavior?

**Comment by srinandan** [comment]
Yes, all the errors turned out to be user errors. The additional validation should hopefully make that clearer.

**Comment by tanmaybangale** [comment]
I am seeing the same observation. 

apigeecli sharedflows import -t "$(gcloud auth print-access-token)" -o gxxxx-demo -f "$(pwd)/sharedflows"

**Comment by Helcaraxan** [comment]
@tanmaybangale what version of apigeecli are you using?

There still has not been a release of a new version that contains the fix. @srinandan any update on that?

**Comment by tanmaybangale** [comment]
well the v1.116 works however I am facing issue with **latest v1.117**

**Comment by Helcaraxan** [comment]
That's expected as it's 1.117 that contains the bug.
