### ISSUE TITLE
bug: envgroups delete does not work

### ISSUE THREAD

**Issue by drush1980** [apigee/apigeecli#159]
The command performs a get instead of a delete:

https://github.com/apigee/apigeecli/blob/8116beb99187e4ade4cc7a9c8da984773b5e8394/cmd/envgroup/delenvgroup.go#L32

**Comment by srinandan** [comment]
This has the fix. I will create a beta release with this fix.

**Comment by srinandan** [comment]
Here is the [beta](https://github.com/apigee/apigeecli/releases/tag/v1.119.1-beta) release.

**Comment by drush1980** [comment]
I'm getting a 404 error when running:

`apigeecli envgroups delete -o $ORG -n $GROUP -t $TOKEN`

**Comment by srinandan** [comment]
Sorry, can you please try [beta 2](https://github.com/apigee/apigeecli/releases/tag/v1.119.2-beta)
