### ISSUE TITLE
Path Checking for `apis create bundle` does not work on Windows OS

### ISSUE THREAD

**Issue by joshwright10** [apigee/apigeecli#162]
When passing a full path to a Proxy Folder on Windows, the following error is returned:
> Error: --proxy-folder or -p must be a path to apiproxy folder

Example command:
`apigeecli apis create bundle --name test-proxy --proxy-folder C:\Temp\bundles\mybundle\apiproxy`.

This is occurring in Windows using PowerShell 7.2.6, however working when running the same script on Ubuntu 21.04 and PowerShell 7.

I see that `path.Base` is used for the path checking. The Golang documentation mentions this regarding the use of the [path](https://pkg.go.dev/path) package:
> This package does not deal with Windows paths with drive letters or backslashes; to manipulate operating system paths, use the path/filepath package.

https://github.com/apigee/apigeecli/blob/2c02207feb92c16d1b7356437b3494ceaf1b0ee6/cmd/apis/bundlecrtapis.go#L54

It might be better to switch to `filepath.Base` in the [filepath](https://pkg.go.dev/path/filepath#Base) package. 
It also looks like this would need to be updated in several other locations.

**Comment by srinandan** [comment]
Thanks for the PR. I have made the changes in other places.
