### ISSUE TITLE
Target server import works correctly but returns an error

### ISSUE THREAD

**Issue by ana-r-goncalves-alb** [apigee/apigeecli#173]
Hi,

When importing a target server, I see that the target server was correctly created in Apigee, but I get the following error:

Error: could not import targetserver, apigee responded with HTTP 200: 200 OK

After checking the source code, I noticed this condition that I think is causing the issue:

https://github.com/apigee/apigeecli/blob/553d525536b71636e79e181dd38571d6959ea7fa/client/targetservers/targetservers.go#L366

Thank you in advance for your time!

**Comment by srinandan** [comment]
This is a case where the import of the target server failed because a) the input was invalid b) the target server already exists. Since you get a 200 OK, I think this is a case where the target server already exists. So it is safe to ignore.

@Helcaraxan FYI

**Comment by ana-r-goncalves-alb** [comment]
This was a case where the target server didn't already exist. A 200 OK response will always trigger an error because the rest of dividing 200 by 100 will be 0 and not 2.

**Comment by srinandan** [comment]
I see your point. I will create a fix for this. Thanks for identifying the issue.

**Comment by srinandan** [comment]
I have submitted a potential fix. Once @Helcaraxan reviews it, I will merge and release a new version.

**Comment by Helcaraxan** [comment]
Apologies for this issue @ana-r-goncalves-alb.

All good on the PR @srinandan. Merge away.

**Comment by srinandan** [comment]
Release v1.119 is published now. Please re-open if there is still an issue.
