### ISSUE TITLE
Apigee - 

### ISSUE THREAD

**Issue by m0xga** [apigee/apigeecli#178]
Hi Team, @srinandan

In the apigee documentation here - you can see that sSLInfo info is a struct:
https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments.targetservers#TargetServer

Here you can see sSLInfo declared as a strut:
https://github.com/apigee/apigeecli/blob/main/internal/client/targetservers/targetservers.go#L46

But here you can see it passed as a string 
https://github.com/apigee/apigeecli/blob/main/internal/client/targetservers/targetservers.go#L64

Which means calls to update the target server configuration are not working as expected.
Could you please help us here?

**Comment by srinandan** [comment]
`sslinfo` is a boolean field. Please see [here]https://github.com/apigee/apigeecli/blob/main/cmd/targetservers/updatets.go#L35

Can you please paste the command you tried? That will help me reproduce the problem.

**Comment by psaini0212** [comment]
Hi @srinandan Thanks for you response as always
To add more details on what @m0xga has shared.
Our requirement is to use **Truststore** field in the target Server.
Agree, sslinfo is a boolean and if set to true it sets all these fields below this line
https://github.com/apigee/apigeecli/blob/main/internal/client/targetservers/targetservers.go#L99
However it looks like we are not setting **Truststore** in this and on that matter not even taking that as an input to this function.
I think if we will add that field that we will be golden here.

**Comment by srinandan** [comment]
I got the problem and I have pushed a new release [here](https://github.com/apigee/apigeecli/releases/tag/v1.120.1-beta). Unfortunately I wasn't able to try it and independently confirm the fix works. Can you please let me know if it worked?

**Comment by psaini0212** [comment]
Thank you kindly @srinandan we will get this tested
