### ISSUE TITLE
Provide ability to "throttle" requests to avoid hitting quota for management APIs.

### ISSUE THREAD

**Issue by kurtkanaskie** [apigee/apigeecli#180]
Customers with many environments hit the quota for Analytics APIs (100 calls per minute) when using:
`apigeecli organizations reports yearly -y 2022 --env-details`

It would be nice if they could set a time delay between each environment. For example:
```
for each env
    for each month
        Get month data
    sleep 10
```
That would set the rate to 72 per minute.
Or some other way to throttle API calls.

**Comment by srinandan** [comment]
According to the [documented](https://cloud.google.com/apigee/docs/api-platform/reference/limits#apigee-apis) limits, we can do 6000 API calls per minute (or 100 per second). I have included some changes that can throttle the rate. I will create a beta release and we can test if the throttling works.

**Comment by srinandan** [comment]
Can you please try this [release](https://github.com/apigee/apigeecli/releases/tag/v1.120.2-beta)?

**Comment by kurtkanaskie** [comment]
Analytics APIs are 100 calls per minute, different from Apigee APIs.
https://cloud.google.com/apigee/docs/api-platform/reference/limits#analytics-apis

 I'll try it out, thanks!

**Comment by srinandan** [comment]
hmm..then I made a mistake. The rate is too high, it is set to 1 every 100 milliseconds. I am going to rework this. Please wait for me to create a new release.

**Comment by srinandan** [comment]
@kurtkanaskie - please try this [release](https://github.com/apigee/apigeecli/releases/tag/v1.120.3-beta) - `v1.120.3-beta`. I'm throttling at 1 API call per second or 60 per minute. This is well below the published limit.

**Comment by kurtkanaskie** [comment]
I tried it out and it works fine. I like the straightforward solution!
