### ISSUE TITLE
API Log Ouput

### ISSUE THREAD

**Issue by cmgpbint** [apigee/apigeecli#184]
I'm trying to get a clean answer as an output from the API requests.

Is there a way to output the **JSON answer** to a file instead of 

`
{
	"environment": "some-env",
	"apiProxy": "some-proxy",
	"revision": "7",
	"deployStartTime": "1680686390307",
	"serviceAccount": "projects/-/serviceAccounts/another"
}

Checking deployment status in 10 seconds
`

or

`
ERROR: 2023/04/05 10:14:26 httpclient.go:372: status code 404, error in response: {
  "error": {
    "code": 404,
    "message": "organizations/apigee/apis/some-proxy/revisions/18 is not deployed",
    "status": "NOT_FOUND",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.RequestInfo",
        "requestId": "14023509995147989598"
      }
    ]
  }
}

Error: error in response
`

**Comment by srinandan** [comment]
can you please list the `apigeecli` command and explain a bit about about the use case?

**Comment by srinandan** [comment]
can you not use `echo $?` to determine if the command passed or failed? That way you don't have to parse the json output.

**Comment by cmgpbint** [comment]
That can also be a great idea, we'll throw generic error to logs -  "Server Error".

I'll close the issue and thanks for the help!

I'll keep the suggestion to keep in backlog
- Add log verbosity
