### ISSUE TITLE
Release v1.120 breaks `downloadLatest.sh` 

### ISSUE THREAD

**Issue by joshwright10** [apigee/apigeecli#195]
Processes using the `https://raw.githubusercontent.com/apigee/apigeecli/main/downloadLatest.sh` installation script no longer work following the release of v1.120.

The script looks for a zip file asset which contain the version number in the name e.g. `apigeecli_v1.119_Linux_x86_64.zip` however v1.120 assets were published without this, and also in `tar.gz` format instead of `zip` e.g. `apigeecli_Linux_x86_64.tar.gz`.

I suggest that the v.1.120 release is re-published in the same way as the previous ones, or the `downloadLatest.sh` script be updated to handle the change in release style while maintaining backwards compatibility. 

Error message:
> Downloading apigeecli_v1.120 from https://github.com/apigee/apigeecli/releases/download/v1.120/apigeecli_v1.120_Linux_x86_64.zip ...
   https://github.com/apigee/apigeecli/releases/download/v1.120/apigeecli_v1.120_Linux_x86_64.zip is not found, please specify a valid APIGEECLI_VERSION and TARGET_ARCH

EDIT: Tagging @srinandan to make sure that this gets better visibility.

**Comment by jonathanmilley** [comment]
Want to raise the profile of this issue, this is impacting our deployment scripts as we download the latest using similar method where we get version number for the latest release and format a URL to match.

**Comment by srinandan** [comment]
I'm so sorry this broke your scripts. We will fix this in the next 30 mins.

**Comment by srinandan** [comment]
This should be fixed now. Please let me know if you still run into problems.

**Comment by joshwright10** [comment]
Thank you @srinandan - just to confirm, is it correct that you meant to change the asset file name format? 

This might break and custom scripts which have been written to  download a version based on input parameter.

**Comment by joshwright10** [comment]
I'm not sure what problems you faced accessing `.Tag` but it should still be accessible [Name Templates - Common Fields](https://goreleaser.com/customization/templates/#:~:text=prefix%20(if%20any)-,.Tag,-the%20current%20git) and it seemed to work ok for me locally. 

I have created a PR with the changes for your review. https://github.com/apigee/apigeecli/pull/198

**Comment by ssvaidyanathan** [comment]
@joshwright10 - Thanks for the PR. Have merged it and re-released all the binaries with the same version v1.120
