### ISSUE TITLE
An OAS with circular schema definitions fails to create API proxy

### ISSUE THREAD

**Issue by kurtkanaskie** [apigee/apigeecli#199]
Given the attached OAS the following command fails with or without --validate false
```
$ apigeecli -t $TOKEN apis create openapi -n leo-clm-basic -f circular-reference.json -o apigeex-payg-kurt --validate false
ERROR: 2023/05/08 09:20:28 generateapi.go:119: kin-openapi bug found: circular schema reference not handled - #/components/schemas/TypeInfo -> #/components/schemas/Type -> #/components/schemas/Type -> #/components/schemas/Type -> #/components/schemas/Type
Error: kin-openapi bug found: circular schema reference not handled - #/components/schemas/TypeInfo -> #/components/schemas/Type -> #/components/schemas/Type -> #/components/schemas/Type -> #/components/schemas/Type
```
Other tools (e.g. openapi2apigee) and the UI to create the proxy and to add an Open API Spec Validation policy, process the OAS without errors.

Rename to circular-reference.json
[circular-reference-json.txt](https://github.com/apigee/apigeecli/files/11421528/circular-reference-json.txt)

**Comment by srinandan** [comment]
I don't think it can be fixed within `apigeecli`. The error is coming from [LoadFile](https://github.com/apigee/apigeecli/blob/main/internal/bundlegen/generateapi.go#L117) and not schema format validation. 

I did detect a problem with how format validation is enabled/disabled. I have fixed that portion.

**Comment by kurtkanaskie** [comment]
I see there was a solution on the kin-openapi repo, the [fix](https://github.com/getkin/kin-openapi/issues/615) was to create a  package-wide CircularReferenceCounter variable.
I added the following to LoadDocumentFromFile and LoadDocumentFromURL in generateapi.go
```
openapi3.CircularReferenceCounter = 100
```
That fixed the issue with the OAS I shared.

**Comment by kurtkanaskie** [comment]
This fix is also needed in LoadDocumentFromURI and I think the value should be higher.
```
openapi3.CircularReferenceCounter = 20
```
For the use case I had, this URL required the circular reference counter to be 11 or greater, value of 10 caused "circular schema reference" error.
```
apis create openapi --import=false -n leo-clm-basic -u https://api-leoaksdev.gep.com/leo-clm-basic/swagger/v1/swagger.json
```
