### ISSUE TITLE
Cannot disable targetserver ssl

### ISSUE THREAD

**Issue by mjooz** [apigee/apigeecli#225]
If a target server is created with SSL enabled, future attempts to disable it seem not to work.
I've tried setting `--sslinfo` and `--tls` to false without success.

It seems that this use case is not covered: https://github.com/apigee/apigeecli/blob/main/internal/client/targetservers/targetservers.go#L98

**Comment by srinandan** [comment]
I was able to get this working by using `--sslinfo=true --tls=false`
