### ISSUE TITLE
Feature request: implement update operation for apps config type

### ISSUE THREAD

**Issue by mjooz** [apigee/apigeecli#241]
Looking at apps API, update operation is supported:
https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.appgroups.apps

**Comment by srinandan** [comment]
It is already implemented [here](https://github.com/apigee/apigeecli/blob/main/docs/apigeecli_appgroups_apps_update.md)

**Comment by mjooz** [comment]
I see, closing.
