### ISSUE TITLE
Unable to update apps created without appgroups attribute

### ISSUE THREAD

**Issue by mjooz** [apigee/apigeecli#245]
Maybe I am missing something, but it seems that apps created before appgroups feature cannot be managed with `appgroups apps` subcommand.  This makes update feature not available for this use case.

If I am right, would it still make sense to implement update for `apigeecli apps` ?

appgroups feature is quite new, still not available in the UI and adoption will take time.

**Comment by srinandan** [comment]
There are two kinds of apps: Developer Apps and AppGroups Apps. Apps created before AppGroups are Developer Apps. They cannot be managed by AppGroups.
