### ISSUE TITLE
Keyaliases update missing --keyFilePath option

### ISSUE THREAD

**Issue by mjooz** [apigee/apigeecli#249]
Tnx for implementing update option. 
It works fine for certificate only, though if we need to update cert/key pair it's missing option for key.

**Comment by kurtkanaskie** [comment]
Update aliases API only supports updating the cert.
https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments.keystores.aliases/update

**Comment by mjooz** [comment]
You're right. Closing.
