### ISSUE TITLE
-a, --account string Flag not working with Service Account JSON key

### ISSUE THREAD

**Issue by flogei** [apigee/apigeecli#26]
Create SA via the CLI
apigeecli iam create -r all -g -p bap-emea-apigee-6

used the generated JSON as follows
apigeecli apis list -o bap-emea-apigee-6 -a safileGenerated.json 

This results in this message:
ERROR: 2022/06/27 12:07:58 token.go:144: status code 400, error in response: {
  "error": "invalid_grant",
  "error_description": "Invalid JWT: Failed audience check. The right audience is https://oauth2.googleapis.com/token"
}

**Comment by srinandan** [comment]
Fixed in: https://github.com/apigee/apigeecli/releases/tag/v1.109-beta.2
