### ISSUE TITLE
Shared flow deploy after create fails when path uses ./ notation

### ISSUE THREAD

**Issue by cygnus8595** [apigee/apigeecli#276]
When creating a shared flow with apigeecli, deploying fails if the shared flow was created with the shared flow path using `./` notation. For example:

If a shared flow is created like so:
```
apigeecli sharedflows create -n $SF_NAME -f $SF_PATH -t $GCLOUD_TOKEN -o $APIGEE_ORG
```
where
```
$SF_PATH="./fromscratch/sharedflowbundle"
```

Deployment will fail with the following error on the console:
```
Status: instance "us-east1" reported error repository.FailedToLoadFile: "Failed to load file : /sharedflows/fromscratch.xml"
```

However, if the path is defined like so:
```
$SF_PATH="fromscratch/sharedflowbundle"
```
The shared flow deploys successfully.

Note that in both cases, the create step is successful.

**Comment by cygnus8595** [comment]
For reference, this is the deploy command:
```
apigeecli sharedflows deploy -n $SF_NAME -e $APIGEE_ENV -t $GCLOUD_TOKEN -o $APIGEE_ORG -r -v $REV
```

**Comment by srinandan** [comment]
I was able to deploy the sharedflow also with this command:

```
apigeecli sharedflows deploy -n sf1 -e prod1 -t $token

{
	"environment": "prod1",
	"apiProxy": "sf1",
	"revision": "2",
	"deployStartTime": "1692808285746"
}
```

**Comment by srinandan** [comment]
To be sure I ran the commands again (matching your flags)

```
apigeecli sharedflows create -n sf1 -f ./test/sharedflowbundle -t $token
{
	"configurationVersion": {
		"majorVersion": 4
	},
	"createdAt": "1692808466927",
	"displayName": "test_flow",
	"entityMetaDataAsProperties": {
		"bundle_type": "zip",
		"subType": "SharedFlow",
		"createdAt": "1692808466927",
		"lastModifiedAt": "1692808466927"
	},
	"lastModifiedAt": "1692808466927",
	"name": "sf1",
	"policies": [
		"Verify-API-Key-1"
	],
	"resourceFiles": {},
	"sharedFlows": [
		"default"
	],
	"type": "Application",
	"revision": "1",
	"description": "undefined"
}

 apigeecli sharedflows deploy -n sf1 -e prod1 -r -v1 -t $token
{
	"environment": "prod1",
	"apiProxy": "sf1",
	"revision": "1",
	"deployStartTime": "1692808487397"
}
```

**Comment by srinandan** [comment]
You can also test this test, I am using a test sharedflow bundle in the [test](https://github.com/apigee/apigeecli/tree/main/test/sharedflowbundle) folder

**Comment by cygnus8595** [comment]
Unfortunately, the deploy response only shows successful deploy start. The UI will show the error I mentioned above.

This is a screenshot of the error in the UI

![image](https://github.com/apigee/apigeecli/assets/2982058/87b6a4c0-4cd9-4b11-aab6-00980417077a)

**Comment by srinandan** [comment]
I still wasn't able to reproduce it.


```
apigeecli sharedflows create -n sf3 -f ./test/sharedflowbundle -t $token
{
	"configurationVersion": {
		"majorVersion": 4
	},
	"createdAt": "1692811596271",
	"displayName": "test_flow",
	"entityMetaDataAsProperties": {
		"bundle_type": "zip",
		"subType": "SharedFlow",
		"createdAt": "1692811596271",
		"lastModifiedAt": "1692811596271"
	},
	"lastModifiedAt": "1692811596271",
	"name": "sf3",
	"policies": [
		"Verify-API-Key-1"
	],
	"resourceFiles": {},
	"sharedFlows": [
		"default"
	],
	"type": "Application",
	"revision": "1",
	"description": "undefined"
}

apigeecli sharedflows deploy -n sf3 -e dev -r -v 1 -t $token
{
	"environment": "dev",
	"apiProxy": "sf3",
	"revision": "1",
	"deployStartTime": "1692811605257"
}

apigeecli sharedflows listdeploy -e dev -n sf3 -r 1
{
	"environment": "dev",
	"apiProxy": "sf3",
	"revision": "1",
	"deployStartTime": "1692811605257",
	"state": "READY",
	"instances": [
		{
			"instance": "us-west1",
			"deployedRevisions": [
				{
					"revision": "1",
					"percentage": 100
				}
			]
		}
	]
}
```

**Comment by cygnus8595** [comment]
OK, so this is getting really weird. I cloned this repo and deployed the test shared flow EXACTLY the same way you did and it worked for me, too. 

However, when I copied the test shared flow into my repo - not even doing anything else to it - the behavior was the same as the issue I'm dealing with. I did see something interesting though. For some reason, it's looking for the wrong xml file in the revision I created with the `./` notation:
```
apigeecli sharedflows listdeploy -e mobility-dev -n sf-test2 -o tcna-nonprod-apigee -t $token -r 3
{
        "environment": "mobility-dev",
        "apiProxy": "sf-test2",
        "revision": "3",
        "deployStartTime": "1692821476473",
        "state": "ERROR",
        "errors": [
                {
                        "code": 2,
                        "message": "instance \"us-east1\" reported error repository.FailedToLoadFile: \"Failed to load file : /sharedflows/test.xml\""
                }
        ],
        "instances": [
                {
                        "instance": "us-east1"
                }
        ]
}
```
These are the commands I used to create and deploy this revision:
```
apigeecli sharedflows create -n sf-test2 -f ./sharedflows/test/test_flow/sharedflowbundle -o tcna-nonprod-apigee -t 
$token
{
        "configurationVersion": {
                "majorVersion": 4
        },
        "createdAt": "1692820943670",
        "displayName": "test_flow",
        "entityMetaDataAsProperties": {
                "createdAt": "1692820943670",
                "lastModifiedAt": "1692820943670",
                "bundle_type": "zip",
                "subType": "SharedFlow"
        },
        "lastModifiedAt": "1692820943670",
        "name": "sf-test2",
        "policies": [
                "Verify-API-Key-1"
        ],
        "resourceFiles": {},
        "sharedFlows": [
                "default"
        ],
        "type": "Application",
        "revision": "3",
        "description": "undefined"
}

apigeecli sharedflows deploy -n sf-test2 -e ce-dev -r -v 3 -o tcna-nonprod-apigee -t $token
{
        "environment": "ce-dev",
        "apiProxy": "sf-test2",
        "revision": "3",
        "deployStartTime": "1692820956999"
}
```

**Comment by cygnus8595** [comment]
Is there any update on this? I ran into the same exact issue with a proxy deployment just now.

**Comment by ssvaidyanathan** [comment]
I just tried the same commands and it worked as expected

```
apigeecli sharedflows create -n sf-test2 -f ./test/sharedflowbundle -o $ORG -t $TOKEN
apigeecli sharedflows create -n sf-test3 -f ./dummy/test/test_sharedflow/sharedflowbundle -o $ORG -t $TOKEN
```

```
apigeecli sharedflows deploy -n sf-test2 -e dev -o $ORG -t $TOKEN -r 1
apigeecli sharedflows deploy -n sf-test3 -e dev -o $ORG -t $TOKEN -r 1
```

```
apigeecli sharedflows listdeploy -e dev -t $TOKEN -o $ORG --->
{
	"deployments": [
		{
			"environment": "dev",
			"apiProxy": "sf-test2",
			"revision": "1",
			"deployStartTime": "1693253449765"
		},
		{
			"environment": "dev",
			"apiProxy": "sf-test3",
			"revision": "1",
			"deployStartTime": "1693253602502"
		}
	]
}
```

**Comment by ssvaidyanathan** [comment]
Are you trying this locally? how did you install apigeecli?

Can you paste the output of `which apigeecli`  from the machine you are testing?

**Comment by cygnus8595** [comment]
This is being done from an apigeecli container from a GitLab CI pipeline. I will get the info shortly; however, the shared flow issue also happened on my local machine, with the following values:

```
global on  ai_typo_fix on ☁️  john.inama@gcp.toyotaconnected.com 
❯ apigeecli --version
apigeecli version 1.122 date: 2023-07-27T20:30:08Z [commit: 9997413]

global on  ai_typo_fix on ☁️  john.inama@gcp.toyotaconnected.com 
❯ which apigeecli
/Users/john.inama/.apigeecli/bin//apigeecli
```

**Comment by cygnus8595** [comment]
Here is the info from the pipeline container:
```
$ apigeecli --version
apigeecli version 1.122 date: 2023-07-27T20:30:08Z [commit: 9997413]
$ which apigeecli
/usr/local/bin/apigeecli
```

**Comment by ssvaidyanathan** [comment]
> 

Thanks for the info. Both @srinandan and I are not able to replicate the issue. Its working from our laptops and we use the same version

**Comment by cygnus8595** [comment]
Thanks for looking, but no, that's not it. Creation works fine, and deploy shows success on apigeecli (because it just checks for the deploy starting) but once deployed, there's an error where it can't find the base xml file. Sometimes it has the name wrong, too. But only when using `./` notation. It's odd and random and really annoying me!! :)

**Comment by ssvaidyanathan** [comment]
@cygnus8595  - we just released a beta version
Can you try installing that and see if the fix works as expected?

```
export APIGEECLI_VERSION=v1.124.0-beta
curl -L https://raw.githubusercontent.com/apigee/apigeecli/main/downloadLatest.sh | sh -
```

**Comment by cygnus8595** [comment]
@ssvaidyanathan I downloaded the latest version and it works:

`❯ apigeecli sharedflows create bundle -n from-scratch -f ./sharedflows/from-scratch/sharedflowbundle -t $token
{
        "configurationVersion": {
                "majorVersion": 4
        },
        "createdAt": "1695241506070",
        "entityMetaDataAsProperties": {
                "bundle_type": "zip",
                "subType": "SharedFlow",
                "createdAt": "1695241506070",
                "lastModifiedAt": "1695241506070"
        },
        "lastModifiedAt": "1695241506070",
        "name": "from-scratch",
        "resourceFiles": {},
        "type": "Application",
        "revision": "11"
}`

`❯ apigeecli sharedflows deploy -n from-scratch -e ce-dev -r -t $token
{
        "environment": "ce-dev",
        "apiProxy": "from-scratch",
        "revision": "11",
        "deployStartTime": "1695241549053"
}`

`{
        "environment": "mobility-dev",
        "apiProxy": "from-scratch",
        "revision": "11",
        "deployStartTime": "1695241637466"
}`

![Screenshot 2023-09-20 at 4 28 51 PM](https://github.com/apigee/apigeecli/assets/2982058/eaf1b9cc-bf63-459d-a92b-3939efb8fc25)

Thanks!

**Comment by ssvaidyanathan** [comment]
Great news! We will release the version in a few days as we consolidate other fixes

Thanks for checking and get back to us
