### ISSUE TITLE
apigeecli targetserver create --grpc needs to add GRPC_TARGET as protocol

### ISSUE THREAD

**Issue by Teodelas** [apigee/apigeecli#284]
Currently apigeecli targetserver create --grpc set the payload as "protocol": "GRPC"

To support gRPC target endpoints protocol should be set to GRPC_TARGET.

GRPC appears to be for external callout policies but mgmt API documentation is also saying this should be changed to EXTERNAL_CALLOUT
https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments.targetservers#TargetServer

**Comment by srinandan** [comment]
I think you have an older version. The newer version of apigeecli does not have that flag:

```
Create a Target Server

Usage:
  apigeecli targetservers create [flags]

Flags:
  -c, --clientAuth string   Enable mTLS for the target server
  -d, --desc string         Description for the Target Server
  -b, --enable              Enabling/disabling a TargetServer (default true)
  -h, --help                help for create
  -s, --host string         Host name of the target
  -i, --ignoreErr string    Ignore TLS validation errors for the target server
      --keyAlias string     Key alias for the target server
      --keyStore string     Key store for the target server
  -n, --name string         Name of the targetserver
  -p, --port int            port number (default -1)
      --protocol string     Protocol for a TargetServer; default is HTTP (default "HTTP")
      --tls string          Enable TLS for the target server
      --trustStore string   Trust store for the target server
```

**Comment by ssvaidyanathan** [comment]
I dont see the --protocol on the latest version

➜  apigeecli git:(main) apigeecli --version
apigeecli version 1.122 date: 2023-07-27T20:30:08Z [commit: 9997413]

➜  apigeecli git:(main) apigeecli targetservers create --help
Create a Target Server

Usage:
  apigeecli targetservers create [flags]

Flags:
  -c, --clientAuth          Enable mTLS for the target server; must be used with sslinfo
  -d, --desc string         Description for the Target Server
  -b, --enable              Enabling/disabling a TargetServer (default true)
  -g, --grpc                Enable target server for gRPC
  -h, --help                help for create
  -s, --host string         Host name of the target
  -i, --ignoreErr           Ignore TLS validation errors for the target server; must be used with sslinfo
      --keyAlias string     Key alias for the target server; must be used with sslinfo
      --keyStore string     Key store for the target server; must be used with sslinfo
  -n, --name string         Name of the targetserver
  -p, --port int            port number (default -1)
      --sslinfo string      Enable SSL Info on the target server
      --tls                 Enable TLS for the target server; must be used with sslinfo
      --trustStore string   Trust store for the target server; must be used with sslinfo

Global Flags:
  -a, --account string   Path Service Account private key in JSON
      --disable-check    Disable check for newer versions
  -e, --env string       Apigee environment name
      --no-output        Disable printing all statements to stdout
  -o, --org string       Apigee organization name
      --print-output     Control printing of info log statements (default true)
  -t, --token string     Google OAuth Token

when I tried passing --protocol to the targetservers create command, I get `Error: unknown flag: --protocol`

**Comment by ssvaidyanathan** [comment]
Should be out in the latest release
