### ISSUE TITLE
Targetservers `--tls false` causes service unavailable (503)

### ISSUE THREAD

**Issue by mjooz** [apigee/apigeecli#286]
If targetserver is created with `--tls false` targetserver is in inconsistent state. If `--tls` is omitted no issues are present. Below is example command which causes service unavailable (targetserver inconsistent state). 

```
apigeecli targetservers create -n TEST --desc "TEST" --host dev.example.com --port 80 --enable true -e dev --tls false
```

Testing with curl: 
```
curl -I -k https://dev.example.com/test
HTTP/2 503
date: Thu, 07 Sep 2023 12:40:11 GMT
via: 1.1 google
```

While workaround is obvious, it may cause issues when `apigeecli` is used programatically with defined values for `tls`.

**Comment by kurtkanaskie** [comment]
For boolean flags you should always use `=`, otherwise it takes the default value. 
I've switched to always use `=` in param assignments.
So in your example, I think you'll have a TS that looks like:
```
apigeecli targetservers create --org=$ORG -n=targetserver-issue-286 --host=mocktarget.apigee.net --port=80 --enable=true --env=dev --tls false
{
	"name": "targetserver-issue-286",
	"host": "mocktarget.apigee.net",
	"port": 80,
	"isEnabled": true,
	"sSLInfo": {
		"enabled": true
	},
	"protocol": "HTTP"
}
```

With `=`
```
apigeecli targetservers create --org=$ORG -n=targetserver-issue-286 --host=mocktarget.apigee.net --port=80 --enable=true --env=dev --tls=false
{
	"name": "targetserver-issue-286",
	"host": "mocktarget.apigee.net",
	"port": 80,
	"isEnabled": true,
	"protocol": "HTTP"
}
```

I do see that the first TS congiguration doesn't work, at least not for the target I tested.

**Comment by ssvaidyanathan** [comment]
@mjooz - the fix was not released
We just pushed a new release v1.123, please test using that
