### ISSUE TITLE
Add support for on-premise enterprise github

### ISSUE THREAD

**Issue by gislikonrad** [apigee/apigeecli#293]
An option should be added to `apigeecli apis create github` to supply an alternative to **https://www.github.com** as the base url. This would help those of us who are running GitHub enterprise on-premise.

Example 
`apigeecli apis create github -n helloworld -u sandbox -r helloworld-proxy -p proxies/helloworld/apiproxy -b https://my.github.local`

**Comment by ssvaidyanathan** [comment]
@gislikonrad - we just released a beta version
Can you try installing that and see if the support for on-prem GitHub works?

```
export APIGEECLI_VERSION=v1.124.0-beta
curl -L https://raw.githubusercontent.com/apigee/apigeecli/main/downloadLatest.sh | sh -
```

**Comment by gislikonrad** [comment]
apigeecli apis create github -g https://git.internal -u infrastructure -r apigee-cloud -p proxies/coffee/apiproxy  -n coffee -o sandbox
Error: unknown shorthand flag: 'g' in -g

**Comment by ssvaidyanathan** [comment]
@gislikonrad - you need to set that as preference
Please check [this](https://github.com/apigee/apigeecli#set-preferences)

**Comment by gislikonrad** [comment]
So, I didn't realize that the `apigeecli` just used http to get the repo. I assumed that it used a preinstalled git client and the associated configuration. GitHub enterprise on-premise requires authentication, even for _public_ repositories. So attempting to use the github feature with on-premise github fails with a 406 status code that attempts to redirect you to a login page. 

Also, when performing `apigeecli prefs set -g <url>`, it overwrites the organization preference.
