### ISSUE TITLE
apigeecli_products_create not able to create API Product with -p API Proxies

### ISSUE THREAD

**Issue by flogei** [apigee/apigeecli#31]
When creating an API Product via this command line sample

apigeecli products create -m "Samples API Product" -e "$APIGEE_X_ENV" -n "Samples API Product" **-p "Proxy A"** -f "auto" -t $APIGEE_TOKEN

The API Product gets created without the API Proxy information so the API Product isnt valid for any Proxy. So it seems the -p parameter gets ignored.

Tried this with different formats but were not successful - it might work but I havent figured out how. So if thats not a bug in the CLI maybe a small sample could be added to the docs page.

**Comment by srinandan** [comment]
Adding proxies directly to an API product is a `legacy` method. This method does not use `operations`. You must use the `--legacy` flag as shown below.

Here is a sample to create an API product via the old method:

```
apigeecli products create -n legacy -m legacy -e prod1 --legacy=true -f auto -p test -t $token
```

output:
```
{
	"name": "legacy",
	"displayName": "legacy",
	"approvalType": "auto",
	"environments": [
		"prod1"
	],
	"proxies": [
		"test"
	],
	"createdAt": "xxx",
	"lastModifiedAt": "xxx"
}
```
