### ISSUE TITLE
Why do we remove apps credentials while import?

### ISSUE THREAD

**Issue by aliasgar55** [apigee/apigeecli#311]
While importing apps why do we remove the credentials and developer id [here](https://github.com/apigee/apigeecli/blob/8e33e2fddacd36f547426a5b7125e12e1f7e9b2b/internal/client/apps/apps.go#L442)

**Comment by srinandan** [comment]
No, this is by design. Importing keys is a three step process:

1) Create a new developer app. This step always generates a new key/secret pair. Since we are importing keys, we do not want this key/secret pair.
2) Delete the auto-generated key pair
3) Import the key.

**Comment by aliasgar55** [comment]
Thanks for the reply
Was not aware for this shortcoming 
Closing this issue out
