### ISSUE TITLE
add --wait for sharedflows deploy

### ISSUE THREAD

**Issue by marcinkubica** [apigee/apigeecli#315]
Hello!

Same as for deploying proxy `--wait` option is really useful in automation.

Currently seems there's no way to check if a sharedflow has completed a deployment since `apigeecli sharedflows listdeploy` doesn't provide this information.

Cheers!

**Comment by kurtkanaskie** [comment]
This has been delivered in the v1.124.1-beta
You can download and try using:
curl -L https://raw.githubusercontent.com/apigee/apigeecli/main/downloadLatest.sh | APIGEECLI_VERSION=v1.124.1-beta sh -
