### ISSUE TITLE
Automated download script fails to verify signature

### ISSUE THREAD

**Issue by mattcolombo** [apigee/apigeecli#324]
When trying to install apigeecli inside an Ubuntu installation under Windows (using WSL), running the command provided in the documentation
```
curl -L https://raw.githubusercontent.com/apigee/apigeecli/main/downloadLatest.sh | sh -
``` 
produces an error with the signature being invalid. However using wget to download the zip file with the binaries and the signature file, and using the command to get `cosign` to validate the package, the validation is working as expected. Please see below screenshot for reference. 
![signature-invalid-evidence](https://github.com/apigee/apigeecli/assets/42300831/8698ecdf-aefa-443f-b0b2-5428be44fd5d)

STEPS TO REPRODUCE:
* run
```
curl -L https://raw.githubusercontent.com/apigee/apigeecli/main/downloadLatest.sh | sh -
```
* observe signature validation error

**Comment by ssvaidyanathan** [comment]
@mattcolombo - can you try now?

**Comment by mattcolombo** [comment]
Looks like it's working fine now! Thanks for the quick help 🙂
M
