### ISSUE TITLE
Issue with apigeecli sharedflows get command

### ISSUE THREAD

**Issue by milufranz08** [apigee/apigeecli#325]
Hello, I'm using this apigeecli command to get the last shared flow revision id so I can then undeploy and delete through a Gitlab pipeline:
`apigeecli sharedflows get -n test-shared-flow`

This is what I'm getting as a response:
```
{
	"metaData": {
		"createdAt": "1698155032595",
		"lastModifiedAt": "1698249519987",
		"subType": "SharedFlow"
	},
	"name": "test-shared-flow",
	"revision": [
		"1",
		"10",
		"11",
		"12",
		"13",
		"14",
		"15",
		"16",
		"17",
		"18",
		"19",
		"2",
		"20",
		"21",
		"22",
		"23",
		"24",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9"
	],
	"latestRevisionId": "9"
}
```

As you can see, it is registering the latestRevisionId as 9 when it is 24. This is blocking me from publishing a pipeline as this is the only way I can see to get the last revision to undeploy using the apigeecli command. Any help will be very appreciated!

**Comment by ssvaidyanathan** [comment]
@milufranz08 

Try this

```sh
REV=$(apigeecli envs deployments get --env "$APIGEE_ENV" --org "$PROJECT" --token "$TOKEN" --sharedflows --disable-check | jq .'deployments[]| select(.apiProxy=="test-shared-flow").revision' -r)
apigeecli sharedflows undeploy --name test-shared-flow --env "$APIGEE_ENV" --rev "$REV" --org "$PROJECT" --token "$TOKEN"
```

**Comment by ssvaidyanathan** [comment]
@milufranz08 - did this work? Can we close this issue?

**Comment by srinandan** [comment]
Please open this issue if @ssvaidyanathan's workaround did not work.
