### ISSUE TITLE
Create or update during import of products

### ISSUE THREAD

**Issue by peruzzof** [apigee/apigeecli#36]
Currently when we try to import an existing product it will just fail with an alert, saying that it already exist.
I belive that the usual approach is to update it when it already exists, so I would love to see the option to update existing products.

With this feature I will be able to create a workflow (git based) to update the products in an automated way. To achieve the same with the current approac (apigeecli products updat) can be harder using other CLI tools (bash, powershell...)

**Comment by srinandan** [comment]
Is the flow you are describing have a file with one or more API Products and you wish to import (create or update as needed) them?

**Comment by peruzzof** [comment]
Yes, I would like to create a file with one or more API products (similar to the one generates with the "product export" command), when I run the import command I wish that everything will be created or updated, as needed)

**Comment by srinandan** [comment]
Unfortunately the API does not support `upsert`. This will double the number of API calls to the control plane. For large data sets, it can affect the quota.

That said, I can see the usefulness of this feature for smaller datasets.
