### ISSUE TITLE
Support OAS 3.1 based API proxy creation

### ISSUE THREAD

**Issue by kurtkanaskie** [apigee/apigeecli#369]
Support OAS 3.1 for `apigeecli apis create openapi`

**Comment by srinandan** [comment]
The package used by apigeecli for OAS is from `https://github.com/getkin/kin-openapi`. This package doesn't support OAS 3.1. Their issue number 230 tracks the discussion for the feature.

We may need to switch to https://quobix.com/articles/parsing-openapi-using-go/ which supports 2.0 (support for Swagger 2.0 is required for API Gateway to Apigee migrations), 3.0 and 3.1. That is a substantial rewrite.
