### ISSUE TITLE
Unable to update app products

### ISSUE THREAD

**Issue by mjooz** [apigee/apigeecli#371]
Standard app products update works just fine.
If I have an app named `test-app` with single product `prod1` I can add (update) products using following command:
```
apigeecli apps keys update --dev "dev@example.com" --name test-app --key [consumerKey] --prods prod2
```

Is there a way I can remove prod2 app using CLI?
Specifying just prod1 app with `--prods prod1` does not remove prod2 product.

**Comment by kurtkanaskie** [comment]
I think that's how the API works, "Adds an API product to a developer app key.
https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.developers.apps.keys/updateDeveloperAppKey

You may have to delete the key, then recreate with new (less) products.
Is that your fix Nandan?

**Comment by srinandan** [comment]
Yes, the fix is to delete all products from the key and add all products supplied from the command line.

**Comment by kurtkanaskie** [comment]
> Not quite. The fix is to delete all products from the key and add all products supplied from the command line.

You're right, upon closer inspection, the UI deletes the product from the key.
https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.developers.apps.keys.apiproducts/delete

**Comment by kurtkanaskie** [comment]
This fix in the "registry" branch LGTM
