### ISSUE TITLE
New feature request to add policies to existing proxy

### ISSUE THREAD

**Issue by wrfleming** [apigee/apigeecli#424]
Description:  Would like to add new policy command feature that would allow the ApigeeCLI to attach a list of policies for example 
ApigeeCLI -policies add -f configfile -n proxy name.  The config file would indicate which flow to attach the policy.  The list of polices would  come from the predefined policies offered in Apigee X today.

**Comment by ssvaidyanathan** [comment]
Closing this issue as its out of scope for the plugin
