### ISSUE TITLE
apigeecli apis clean - does not deletes undeployed/unused proxy revisions

### ISSUE THREAD

**Issue by ametelski** [apigee/apigeecli#44]
I would like to use this command in my CICD pipeline, but it just returns the current deployed proxy revision and a report of the revisions that can be cleaned. Is the expected result of the command? if so could this command be enhanced to return a json object.

```
> apigeecli apis clean -o $org -t $token -n $proxy
Revisions [20] deployed for API Proxy testing
[REPORT]: API Proxy 'testing' revisions: 10,11,12,6,1,14,15,16,3,8,13,2,4,5,7,9,17,18,19 can be cleaned
```

**Comment by srinandan** [comment]
Here is the help for `clear`:

`Deletes undeployed/unused reivisions of an API proxy

Usage:
  apigeecli apis clean [flags]

Flags:
  -h, --help                   help for clean
  -k, --keepList stringArray   List of revisions to keep, -k 1 -k 2
  -n, --name string            API proxy name
      --report                 Report which API proxy revisions will be deleted (default true)`

By default `--report` is enabled.  Deleting a proxy is permanent. We don't want users to accidentally delete revisions (there is no recovery). Therefore you are seeing a list of versions that can be cleaned. The user may rerun the command with `--report=false` and remove all those reported versions. Conversely, the user may rerun with `--report=false` and `--keepList` and specify which revisions to keep.

**Comment by ametelski** [comment]
Yes that was it. Changing `--report=false` deleted the undeployed proxies. Thanks,
