### ISSUE TITLE
Create an OAS type resource 

### ISSUE THREAD

**Issue by andreuji** [apigee/apigeecli#440]
In the apigeecli resources create command, it is not possible to create a resource of type oas:

> Error: invalid resource type

But it is possible through googleapis.

Could you implement support for creating this type of resource?

**Comment by srinandan** [comment]
The latest release [v2.0.1](https://github.com/apigee/apigeecli/releases/tag/v2.0.1) which was released yesterday has this enhancement.

**Comment by ssvaidyanathan** [comment]
@andreuji - we just re-released the version with the docs/help update. Please re-install apigeecli and let us know if you still have issues
