### ISSUE TITLE
add option to specify control plane host

### ISSUE THREAD

**Issue by dfong** [apigee/apigeecli#462]
in staging, we use the host staging-apigee.sandbox.googleapis.com instead of apigee.googleapis.com.  does apigeecli have an option to specify the control plane host?  without such an option, we can't use apigeecli in staging.

apigeecli is used by scripts in the apigee-samples repo and the apigee/devrel repo.  so, the lack of this option in apigeecli means these other repos also can't be used in staging.

**Comment by DinoChiesa** [comment]
lightning fast!
