### ISSUE TITLE
Missing option to configure "Strictly enforce SSL" option for Targetservers

### ISSUE THREAD

**Issue by mjooz** [apigee/apigeecli#474]
Hi,

Among existing switches for `apigeecli targetservers create` I can not find one for configuring "Strictly enforce SSL". This option is present in the UI.

Can we add this?

**Comment by ssvaidyanathan** [comment]
fixed and released in v2.2.0-beta.2

Please try it and let us know. To install this version

```sh
export APIGEECLI_VERSION=v2.2.0-beta.2
curl -L https://raw.githubusercontent.com/apigee/apigeecli/main/downloadLatest.sh | sh -
```

**Comment by mile-misan** [comment]
Tried. Works as expected. Thanks a lot.

**Comment by mjooz** [comment]
Works as expected, thanks a lot.
