### ISSUE TITLE
kvm entries update command is not accepting true/false as the key value

### ISSUE THREAD

**Issue by andreuji** [apigee/apigeecli#496]
In release v2.2.0 the kvm entries update command is not accepting true/false as the key value.
This new rule broke the logic of our automation pipeline.
Is there any way around it or would it be possible to accept true/false values ​​in this command again?

![Captura de tela 2024-07-05 112458](https://github.com/apigee/apigeecli/assets/8531959/93a6d162-b4a5-4cf8-863c-0a6b02489b28)

**Comment by ssvaidyanathan** [comment]
@andreuji - to test this out, can you please share the command you are running?

**Comment by andreuji** [comment]
@ssvaidyanathan 

apigeecli kvms entries update -m <mapname> -k teste__kvm -l true -o <org> --env <env> -a ./sa-devops.json
