### ISSUE TITLE
universal binaries for mac

### ISSUE THREAD

**Issue by srinandan** [apigee/apigeecli#50]

**Comment by waheedbrown** [comment]
Also noticed this issue on macOS Monterey version 12.5, Macbook Pro (14 inch, 2021), running an Apple M1 Pro chip (ARM 64 architecture)

Steps to reproduce:
1. Run apigeecli installation curl request:
```
curl -L https://raw.githubusercontent.com/apigee/apigeecli/master/downloadLatest.sh | sh -
```
2. The following error message is returned once the download completes and `downloadLatest.sh` is run:
```
This system's architecture, arm64, isn't supported
```

Recommended fix:
* Make sure arm64 is not one of the excluded architectures, when building the apigeecli in Xcode
* Details are in the following Apple Developer Forum post: [Arm64 in excluded architectures - how to use?](https://developer.apple.com/forums/thread/679708)

**Comment by paulprogrammer** [comment]
Note: using the x86 build downloaded manually works on the M1 macs.
