### ISSUE TITLE
Create a proxy with pre existing oauth2 policies

### ISSUE THREAD

**Issue by adielskaistyael** [apigee/apigeecli#502]
I have been trying to create a proxy that is using an oauth2 policy with the operation VerifyAccessToken. It seems possible when i look at the file: apigeecli/internal/bundlegen/policies/policies.go lines 38-49, but I don't understand exactly how.

**Comment by srinandan** [comment]
Depending on where you want the policies added, you can choose one of the two methods:

- Adding it to the preflow. Here's an example for [OAuth](https://raw.githubusercontent.com/apigee/apigeecli/main/test/minspec-oauth.yaml) and [VerifyAPI Key](https://raw.githubusercontent.com/apigee/apigeecli/main/test/minspec-apikey.yaml). You can also merge them to add both
- Use an OpenAPI spec to add them to the flow. Here's an [example](https://github.com/apigee/apigeecli/blob/main/test/petstore-v3.1.yaml)
