### ISSUE TITLE
org import fails while importing Apps

### ISSUE THREAD

**Issue by valemrt** [apigee/apigeecli#506]
The organizations import command fails while importing Apps with the following error (screenshot attached) 
```
ERROR: 2024/07/16 17:21:53 apps.go:350: error reading file:  invalid character '"' after top-level value
Error: invalid character '"' after top-level value
```
![image](https://github.com/user-attachments/assets/859e9c13-1729-4eec-80b6-3e99b2920cb8)

**Comment by srinandan** [comment]
Please note, the PR does *not* address the problem posted. But I observed a different problem when troubleshooting and tracking it as part of the same issue.

**Comment by srinandan** [comment]
The issue noted here is not bug. Leaving this issue open to handle the print statements.

**Comment by kurtkanaskie** [comment]
I didn't get to test this, if it's not a bug, what is causing the error?
