### ISSUE TITLE
Total API call factor-in Extensible / Standard API calls

### ISSUE THREAD

**Issue by welylau** [apigee/apigeecli#521]
In the new Apigee pricing (and the Subscription 2024), there's a distinction between Standard vs Extensible call in which 5 x Standard calls are counted as 1 Extensible call?

The result is of this cli https://github.com/apigee/apigeecli/blob/main/docs/apigeecli_organizations_reports.md is
currently combined.

This issue / request is to make the cli has an option to:
- define API call types (Standard vs Extensible)
- for the total, there needs to be the "effective total" in which 5 standard call is counted as 1

**Comment by kurtkanaskie** [comment]
There's a dimension for this "proxy_deployment_type".
![image](https://github.com/user-attachments/assets/e0e90100-f3b0-4635-9ba8-e428b37ce4af)
