### ISSUE TITLE
question regarding gcloud cli integration apigee

### ISSUE THREAD

**Issue by sdrzazga-nsd** [apigee/apigeecli#529]
Hi.

Can you tell me if there is a plan to eventually fully integrate Today's Apigee CLI` capabilities into the `gcloud CLI` or if they will be deliberately kept separate?
Thanks in advance for your help.

**Comment by ssvaidyanathan** [comment]
May be @gsjurseth can help

**Comment by gsjurseth** [comment]
There are plans to expand the capabilities of gcloud for apigee, but no specific plans to expand it with everything apigeecli does today. Is there a specific capability you're looking for?

**Comment by sdrzazga-nsd** [comment]
The functionality that is available today through the gcloud CLI  is not very helpful for the aspect of automation, so we would never use it.
To decide on our end what CLIs matter for the work with Apigee we wanted to understand if there is a plan to eventually reconsolidate the CLI tooling and move it perhaps as a component into the gcloud CLI.

**Comment by srinandan** [comment]
Closing this issue. Please re-open if your question wasn't answered.
