### ISSUE TITLE
 `apigeecli environments debugmask set` uses POST instead of PATCH and does not handle JSON arrays correctly

### ISSUE THREAD

**Issue by narhen** [apigee/apigeecli#530]
**Version:** apigeecli version 2.4.0 date: 2024-08-21T16:56:04Z [commit: e96358f]

When running the command:
```bash
apigeecli environments debugmask set --token <token> --org <organisation> --env <environment> --mask-file debugmask.json
```

with the contents of the `debugmask.json` being:
```json
{
    "variables": [
        "request.header.x-api-key",
        "request.header.x-apikey"
    ]
}
```
(taken from the [samples/debugmask.json](https://github.com/apigee/apigeecli/blob/main/samples/debugmask.json) file in the repository), the following error is thrown by apigeecli:
```
Error: json: cannot unmarshal array into Go value of type string
```

It seems that this happens because the tool is trying to deserialize the JSON into a string-string key-value pair, as seen in the following part of the code: https://github.com/apigee/apigeecli/blob/main/internal/client/env/debugmask.go#L35-L39.

When I modify the JSON file to specify a string key-value pair like this:
```json
{
    "variables": "request.header.x-apikey"
}
```
the deserialization error disappears, but the command still fails, returning a 404 error page from Google:
```
Error: Not found - the server cannot find the requested resource
```

### Reproduction Steps

1. Run the following command:
```bash
apigeecli environments debugmask set --token <token> --org <organisation> --env <environment> --mask-file debugmask.json
```
With `debugmask.json` containing:
```json
{
    "variables": [
        "request.header.x-api-key",
        "request.header.x-apikey"
    ]
}
```
2. The following error occurs:
```
Error: json: cannot unmarshal array into Go value of type string
```
3. After changing the debugmask.json to a string:
```json
{
    "variables": "request.header.x-apikey"
}
```
4. The command returns:
```
Error 404 (Not Found)
```

### Additional Information

* When running apigeecli in debug mode, it shows that a `POST` request is sent to the API:
```bash
APIGEECLI_DEBUG=true apigeecli environments debugmask set --token <token> --org example-org --env example-env --mask-file debugmask.json
```
Debug output:
```
DEBUG: Connecting to: POST - https://apigee.googleapis.com/v1/organizations/example-org/environments/example-env/debugmask
```
* However, according to the official Apigee documentation, a PATCH request should be used instead: https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments/updateDebugmask
* Additionally, the expected request body format is not a string key-value pair as the current implementation suggests. The correct request body structure is outlined in the documentation: https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/DebugMask

### Suggested Fix
* Change the HTTP method from `POST` to `PATCH` as per the official documentation.
* Update the JSON handling logic to follow the correct structure from the documentation, where arrays like `"variables"` should be supported rather than string key-value pairs.

**Comment by srinandan** [comment]
Thanks for the detailed issue. I have created a fix, it will be part of `v2.4.1`

**Comment by ssvaidyanathan** [comment]
@narhen - pls test using 2.4.1 and let us know if you still see the issue.

**Comment by narhen** [comment]
Works perfectly with 2.4.1. Thanks!
