### ISSUE TITLE
Publish apigeecli Documentation failed during release

### ISSUE THREAD

**Issue by kurtkanaskie** [apigee/apigeecli#542]
[Publish apigeecli Documentation](https://github.com/apigee/apigeecli/actions/runs/10962404586/job/30441560942)

The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

**Comment by srinandan** [comment]
This has been fixed now.
