### ISSUE TITLE
No error status and  detail message are returned when deploying a proxy revision to an apigee environment without active runtime pods

### ISSUE THREAD

**Issue by joaoorosario** [apigee/apigeecli#591]
**Describe the bug**
No error status code and detail message are returned when deploying a proxy revision to an apigee environment without active runtime pods.
Here is a screenshot when trying to deploy latest available revision to such an environment:
![Screenshot 2024-12-03 142244](https://github.com/user-attachments/assets/4f8943b8-b7a6-43e3-8e07-0694fed343a6)

**Version**
2.7.0

**To Reproduce**
The environment must not have active runtime pods. Try to deploy any revision to it.

**Expected behavior**
An error status code should be returned and also a detail message of the error

**Comment by ssvaidyanathan** [comment]
fixed and released in v2.7.1
