### ISSUE TITLE
[FR] Data privacy region - different url of Apigee API

### ISSUE THREAD

**Issue by kacperillo** [apigee/apigeecli#607]
Since our GCP organization is set only within specific region (in our case Germany) due to data privacy concerns, we can't use apigeecli tool - the url of the Apigee API is `https://de-apigee.googleapis.com`. 

For example if I run command `apigeecli organizations list -t $TOKEN`, I receive an empty list. However when I send a request directly to the correct url of Apigee API (https://de-apigee.googleapis.com/v1/organizations) - I successfully get a list with my organization.

If it was a chance to choose the specific region as a parameter/flag with the apigeecli command or at least type manually the base url of Apigee API, then it would work correctly also for such scenarios.

**Comment by kurtkanaskie** [comment]
That is supported using the --region flag
-r, --region string   Apigee control plane region name; default is https://apigee.googleapis.com

apigeecli organizations --region=de list

**Comment by srinandan** [comment]
The region can also be set as a preference using `apigeecli preferences set -r` and that region will be used in subsequent calls.

**Comment by srinandan** [comment]
Closing this issue. Please re-open if the cli doesn't work as expected.
