### ISSUE TITLE
[BUG] Unable to update API Products

### ISSUE THREAD

**Issue by brunoselistre-dvt** [apigee/apigeecli#619]
**Description**
apigeecli product update command always return "Invalid ApiProduct Name". It works to get products *(apigeecli get)* from apigeecli but when I try to update any product the it returns an error

- `apigeecli products get -n "demo"` - returns success
- `apigeecli products update -n "demo" -f auto ` - returns 400 Invalid ApiProduct Name

Error msg: 
`
{
  "error": {
    "code": 400,
    "message": "Invalid ApiProduct Name",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.PreconditionFailure",
        "violations": [
          {
            "type": "keymanagement.service.apiproduct_invalid_displayname",
            "subject": "[2002:a05:6693:7acc:b0:91:d031:3cb0]:4001:acparo13-2a0014508059000d00b0002aca211494:9801:201896:171730949",
            "description": "Invalid ApiProduct Name"
          }
        ]
      },
      {
        "@type": "type.googleapis.com/google.rpc.RequestInfo",
        "requestId": "13260319205678465776"
      }
    ]
  }
}
` 

*Note:  I have tried with multiple products and properties but the output is always the same error*

**Version**
apigeecli version 2.7.1 date: 2024-12-05T23:01:06Z [commit: ef1fda1]

**Comment by srinandan** [comment]
Display Name is a mandatory field when updating the product. I have fixed it by making it so. In the meanwhile, you can fix the command by passing `-m` or `--display-name` to the command.

**Comment by ssvaidyanathan** [comment]
@brunoselistre-dvt - pls try using v2.8.1 (latest)
It should mandate the displayName and approval fields that are mandatory while updating the product.
