### ISSUE TITLE
More clarity into how to use apigeecli apis import

### ISSUE THREAD

**Issue by carlosmscabral** [apigee/apigeecli#81]
Docs/help messages are vague in terms of how to use apigeecli apis import. Should we point to a folder with zip files? To folder with the apiproxy/ structure?

It is not clear.

If I issue this command:

 apigeecli apis import -o $APIGEE_ORG  -t $(gcloud auth print-access-token) --folder=./apiproxy

No errors are generated and no proxies get deployed whatsoever.

**Comment by srinandan** [comment]
This command is not to import a single proxy. It is meant to import many proxy bundles.

```
apigeecli apis import -o $ORG -t $TOKEN --folder=./proxies
```
The proxies folder must contain one or more proxy bundle zip files.

If you want to import a single proxy, try the `apigeecli apis create` command.
