### ISSUE TITLE
Use in GCP cloud shell

### ISSUE THREAD

**Issue by nando-carvalho** [apigee/apigeecli#87]
**This worked for me**

Access: @cloudshell:~/.apigeecli/bin 
Inside the bin folder use the commands always running: ./apigeecli, like: ./apigeecli kvms list. 

I think it would be interesting to have more details in the  Readme file.

**Comment by srinandan** [comment]
You could add ~/.apigee/bin to the PATH like so:

```sh
export PATH=$PATH:~/.apigeecli/bin
```

and even add this to the bash profile so it is always added.
