### ISSUE TITLE
Use a temporary folder to generated bundle for "create apis" command

### ISSUE THREAD

**Issue by peruzzof** [apigee/apigeecli#96]
Using the apigeecli inside an Azure DevOps is leading to an error during the removal of the zip created (https://github.com/apigee/apigeecli/blob/65fb892bdbd5abeeb95e656c67645e80bbdfd928/cmd/apis/bundlecrtapis.go#L46), so I would like to have the option to generate the temporary file in an arbitrary folder.

Just to give more context, every time that I execute the command:
apigeecli.exe apis create bundle -o '${{ parameters.organization }}' -n $apiname -p $apiname/apiproxy 

I get the error:
Error: remove ##REDACTED##.zip: The process cannot access the file because it is being used by another process.

I guess that there is some background job that is scanning the file, but as this is a Microsoft owned environment I cannot be sure. The only issue is that the temporary file is being copied to my artifact folder and I dont want to add a second command to remove it (while technically is possible)

**Comment by srinandan** [comment]
This PR should address the issue: https://github.com/apigee/apigeecli/pull/97

If you are able to try a `beta` release, I can publish a new release with these changes.

**Comment by peruzzof** [comment]
Yes, I can. Let me know when it is ready and I will test it ASAP

**Comment by srinandan** [comment]
Can you please try this beta release: https://github.com/apigee/apigeecli/releases/tag/v1.113.1-beta

There is a new `-f` (output folder) to write the bundle. This could be in `/tmp`

**Comment by peruzzof** [comment]
Thanks, the flag is working as expected, but the issue remains, I will keep using the new flag as I believe that is a best practice and will raise a ticket with Microsoft to understand the root cause.

Just to share, the error message now is:
Error: remove **D:\a\_temp**/##REDACTEC##.zip: The process cannot access the file because it is being used by another process.

**Comment by srinandan** [comment]
I noticed that we weren't closing the [file](https://github.com/apigee/apigeecli/blob/main/bundlegen/proxybundle/proxybundle.go#L346). I have added that. I will create another build and see if that helps.

**Comment by srinandan** [comment]
Can you please try with this [binary](https://github.com/apigee/apigeecli/releases/tag/v1.113.2-beta)?

**Comment by peruzzof** [comment]
Thanks, the issue is fixed with the new v1.113.2-beta version.

**Comment by srinandan** [comment]
This is now available with v1.113
